##Предварительно выполнить на Linux хосте команду: sudo sysctl -w vm.max_map_count=262144
##https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144
#
##kibana address: http://127.0.0.1:5601 будет доступно через ~1-2 мин
#
services:

  es-hot:
    image: elasticsearch:8.7.0
    container_name: es-hot
    environment:
      - node.name=es-hot
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-hot,es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - node.roles=master,data_content,data_hot  
      - "ES_JAVA_OPTS=-Xms2000m -Xmx2000m"
      - "http.host=0.0.0.0"
      - xpack.security.enabled=false
    volumes:
      - es-hot-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    mem_limit: 2g
    networks:
      - elastic
    depends_on:
      - es-warm

  es-warm:
    image: elasticsearch:8.7.0
    container_name: es-warm
    environment:
      - node.name=es-warm
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-hot,es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - node.roles=master,data_warm
      - "ES_JAVA_OPTS=-Xms2000m -Xmx2000m"
      - xpack.security.enabled=false
      - "http.host=0.0.0.0"
    volumes:
      - es-warm-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    networks:
      - elastic

  kibana:
    image: kibana:8.7.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es-hot:9200
      ELASTICSEARCH_HOSTS: '["http://es-hot:9200","http://es-warm:9200"]'
    mem_limit: 512m
    networks:
      - elastic
    depends_on:
      - es-hot
      - es-warm

  logstash:
    image: logstash:8.7.0
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 5046:5046
      - 5044:5044
    mem_limit: 512m
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - elastic
    depends_on:
      - es-hot
      - es-warm

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.0
    container_name: filebeat
    privileged: true
    user: root
    command: /usr/share/filebeat/filebeat -e -strict.perms=false
    mem_limit: 512m
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /k8s/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      - elastic

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    mem_limit: 512m
    volumes:
      - ./pinger/:/opt/
    entrypoint: python3 /opt/run.py
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  es-hot-data:
    driver: local
  es-warm-data:
    driver: local
