[tox]
minversion = 1.8
basepython = python3.9
envlist = py39-ansible210
skipsdist = true

[testenv]
passenv = *
deps =
    setuptools<60
    ansible==2.10.7
    ansible-base==2.10.17
    molecule==3.4.0
    ansible-lint==5.4.0
    git+https://github.com/ansible-community/molecule-podman.git@0.3.0
    testinfra
    -r tox-requirements.txt

commands =
    molecule test -s light --destroy always
