---
- name: Install Clickhouse
  hosts: clickhouse
  tags:
    - clickhouse
  roles:
    - clickhouse-role

- name: Install Vector
  hosts: localhost
  tags:
    - vector
    - docker-vector
    - systemd-vector
    - helm
  pre_tasks:
    - name: Install community.docker collection
      ansible.builtin.command: ansible-galaxy collection install community.docker
      changed_when: false
      tags:
        - docker-vector
  roles:
    - vector-role
