[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/a/.ato4ka/security/.ssh/id_ed25519
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o ConnectTimeout=30
ansible_connection_timeout=30
ansible_python_interpreter=/usr/bin/python3

[marketing]
develop-webs-0 ansible_host=89.169.147.5 fqdn=develop-webs-0.ru-central1.internal
develop-webs-1 ansible_host=89.169.164.173 fqdn=develop-webs-1.ru-central1.internal

[analytics]
stage-web-stage-0 ansible_host=84.252.130.218 fqdn=stage-web-stage-0.ru-central1.internal
