---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_facts['distribution'] }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"