{
 "title": "netol2",
 "tags": [ "node-exporter" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"node_exporter_docker\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_exporter_docker\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"node_exporter_docker\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"node_exporter_docker\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Free Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node_exporter_docker\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Filesystem Free Space (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node_exporter_docker\",fstype!=\"tmpfs|devtmpfs|sshfs|squashfs|overlay\"} / 1024 / 1024 / 1024"
    }
   ]
  }
 ]
}