---
apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app.kubernetes.io/name: netology
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: web 
  namespace: default
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    name: netology-web-01
    ports:
    - containerPort: 8080
