---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy docker instances
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
      when: molecule_yml.platforms is defined
