---

- name: Yum - Add Nginx Repo
  become: true
  ansible.builtin.copy:
    dest: "/etc/yum.repos.d/nginx-stable.repo"
    mode: "0644"
    content: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true
  when: ansible_facts['os_family'] == "RedHat"
  tags: lighthouse

- name: Yum - Install packages
  become: true
  ansible.builtin.dnf:
    disable_gpg_check: true
    name:
      - git
      - nginx
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  tags: lighthouse
